delete from global_property where property like 'birt.%';

INSERT INTO global_property (property,property_value,description,uuid) VALUES ('birt.birtHome','/var/lib/birt/ReportEngine','@HOME@/.OpenMRS/reports/datasets','d03cc925-fa3f-4f64-9292-a5ee7b991652');
INSERT INTO global_property (property,property_value,description,uuid) VALUES ('birt.datasetDir','@HOME@/.OpenMRS/reports/datasets','Specifies the absolute path to the reports dataset directory (for CSV/XML data sources).','dac4f6fa-4373-4562-97cd-6dbfa17c6c2c');
INSERT INTO global_property (property,property_value,description,uuid) VALUES ('birt.defaultReportDesignFile','default.rptdesign','Specifies the absolute path to the reports dataset directory (for CSV/XML data sources).','f1fae7b2-9a1c-42a1-9f68-14cee21e91fc');
INSERT INTO global_property (property,property_value,description,uuid) VALUES ('birt.imageDir','@HOME@/.OpenMRS/reports/output/images','Specifies the absolute path to the image directory where BIRT will find generated charts and graphs.','9f8f0383-4c19-4d53-bf1c-148d1d0d6677');
INSERT INTO global_property (property,property_value,description,uuid) VALUES ('birt.loggingDir','@HOME@/.OpenMRS/reports/logs','Specifies the absolute path for log files written by BIRT Engine','26ab7d81-7d77-4fa0-adcf-3a2b226ff5a3');
INSERT INTO global_property (property,property_value,description,uuid) VALUES ('birt.mandatory','false','true/false whether or not the birt module MUST start when openmrs starts.  This is used to make sure that mission critical modules are always running if openmrs is running.','ac4e8626-9209-44dd-8dd3-b5af60022540');
INSERT INTO global_property (property,property_value,description,uuid) VALUES ('birt.outputDir','@HOME@/.OpenMRS/reports/output','Specifies the absolute path to the report output file when reports are generated','0b1388bd-5652-4e92-a838-a39cf0dbca49');
INSERT INTO global_property (property,property_value,description,uuid) VALUES ('birt.reportDir','@HOME@/.OpenMRS/reports','Specifies the absolute path where report design files are uploaded.','955cacaf-9e62-4a5b-88aa-981c085e408a');
INSERT INTO global_property (property,property_value,description,uuid) VALUES ('birt.reportOutputFile','','Specifies the absolute path to the reports output file.  (ex. C:/Documents and Settings/USERNAME/OpenMRS/reports/output/ReportOutput.pdf)','6e3ec154-f198-455e-a97f-48a933e6961a');
INSERT INTO global_property (property,property_value,description,uuid) VALUES ('birt.reportOutputFormat','xls','Specifies the absolute path to the reports output format.(ex. pdf)','7ded45fa-0d1d-4d66-857d-41687d443242');
INSERT INTO global_property (property,property_value,description,uuid) VALUES ('birt.reportPreviewFile','','Specifies the absolute path to the report preview file.  (ex. C:/Documents and Settings/USERNAME/OpenMRS/reports/output/ReportPreview.pdf)','3eb99933-8179-4fd1-b0f3-2fd63663a491');
INSERT INTO global_property (property,property_value,description,uuid) VALUES ('birt.started','false','DO NOT MODIFY. true/false whether or not the birt module has been started.  This is used to make sure modules that were running  prior to a restart are started again','d02d3c5d-a7dd-4027-a9cf-b6d7c393255a');
