#!/usr/bin/ruby

tomcat_host=ARGV[0]

if(ret = %x[curl http://#{tomcat_host}:8080/stepsovc/index.html]) =~ /Hello world/
	puts "Tomcat OK"
	exit(0)
else
	puts "'curl http://#{tomcat_host}:8080/stepsovc/index.html' returned #{ret.strip}"
	exit(2)
end
